### ISSUE TITLE
spinn_common doesn't compile

### ISSUE THREAD

**Issue by arrenglover** [SpiNNakerManchester/spinn_common#26]
I get the following error when running "make" in the main directory:

![image](https://user-images.githubusercontent.com/9265237/43575423-18407a56-9647-11e8-9a14-82e8d9131750.png)

I guess something from the most recent merge with inline functions.

**Comment by andrewgait** [comment]
Yes - you need to clean the relevant files out of spinnaker_tools/include, and our makefiles don't currently let you do that automatically.  I've got a branch / pull request where I've added the capability to do so using "make install-clean" here: https://github.com/SpiNNakerManchester/spinn_common/pull/25 so you could use that branch for now.

**Comment by arrenglover** [comment]
Thanks @andrewgait .  Your branch worked. Please close this issue once the merge-request goes though.
